mappings:
  EcommerceNewsletterCampaignMonitorSignupDecoratorFormFixes: Sunnysideup\EcommerceNewsletterCampaignMonitor\Extensions\EcommerceNewsletterCampaignMonitorSignupDecoratorFormFixes
  EcommerceNewsletterCampaignMonitorSignupDecoratorConfigFixes: Sunnysideup\EcommerceNewsletterCampaignMonitor\Extensions\EcommerceNewsletterCampaignMonitorSignupDecoratorConfigFixes
