---
Name: ecommerce_newsletter_campaign_monitor
Before: 'app/*'
After: ['#coreconfig', '#cmsextensions', '#ecommerce']
---
Sunnysideup\Ecommerce\Forms\OrderFormAddress:
  extensions:
    - Sunnysideup\EcommerceNewsletterCampaignMonitor\Extensions\EcommerceNewsletterCampaignMonitorSignupDecoratorFormFixes
Sunnysideup\Ecommerce\Model\Config\EcommerceDBConfig:
  extensions:
    - Sunnysideup\EcommerceNewsletterCampaignMonitor\Extensions\EcommerceNewsletterCampaignMonitorSignupDecoratorConfigFixes
