---
Name: ecommerce_newsletter_campaign_monitor
Before: 'app/*'
After: ['#coreconfig', '#cmsextensions', '#ecommerce']
---
OrderFormAddress:
  extensions:
    - EcommerceNewsletterCampaignMonitorSignupDecoratorFormFixes

EcommerceDBConfig:
  extensions:
    - EcommerceNewsletterCampaignMonitorSignupDecoratorConfigFixes

